name: PyInstaller Workflow

on:
  push:
    paths:
      - "D:/Desktop/Recursive-Counter/counter.py"
  pull_request:
    paths:
      - "D:/Desktop/Recursive-Counter/counter.py"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Build executable
        run: pyinstaller --noconfirm --onefile --console "D:/Desktop/Recursive-Counter/counter.py"
